#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : argparse
Version  : 1.4.0
Release  : 6
URL      : https://pypi.python.org/packages/source/a/argparse/argparse-1.4.0.tar.gz
Source0  : https://pypi.python.org/packages/source/a/argparse/argparse-1.4.0.tar.gz
Summary  : Python command-line parsing library
Group    : Development/Tools
License  : Python-2.0
Requires: argparse-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
The argparse module makes it easy to write user friendly command line
interfaces.

%package python
Summary: python components for the argparse package.
Group: Default

%description python
python components for the argparse package.


%prep
%setup -q -n argparse-1.4.0

%build
python2 setup.py build -b py2

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
